name: Deploy to server
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: test
        run: |
          pwd
          ls -la
      - name: Compress dist files
        run: tar -zcvf ./product/dist.tar ./dist/angular-admin
      - name: Copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: ./product/dist.tar
          target: ${{ secrets.WWW_PATH }}/angular-admin/product/
      - name: Exec deploy script with SSH
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sh ${{ secrets.WWW_PATH }}/angular-admin/.deploy/main.sh
